/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppLayoutImport } from './routes/_app/_layout'
import { Route as AppLayoutIndexImport } from './routes/_app/_layout/index'
import { Route as AppLayoutWelcomeIndexImport } from './routes/_app/_layout/welcome/index'
import { Route as AppLayoutSubscribeIndexImport } from './routes/_app/_layout/subscribe/index'
import { Route as AppLayoutSearchIndexImport } from './routes/_app/_layout/search/index'
import { Route as AppLayoutFoldersIndexImport } from './routes/_app/_layout/folders/index'
import { Route as AppLayoutFavouritesIndexImport } from './routes/_app/_layout/favourites/index'
import { Route as AppLayoutFaqSupportIndexImport } from './routes/_app/_layout/faq-support/index'
import { Route as AppLayoutSoundNameImport } from './routes/_app/_layout/sound/$name'
import { Route as AppLayoutSubscribePaymentIndexImport } from './routes/_app/_layout/subscribe/payment/index'

// Create/Update Routes

const AppLayoutRoute = AppLayoutImport.update({
  id: '/_app/_layout',
  getParentRoute: () => rootRoute,
} as any)

const AppLayoutIndexRoute = AppLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutWelcomeIndexRoute = AppLayoutWelcomeIndexImport.update({
  id: '/welcome/',
  path: '/welcome/',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutSubscribeIndexRoute = AppLayoutSubscribeIndexImport.update({
  id: '/subscribe/',
  path: '/subscribe/',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutSearchIndexRoute = AppLayoutSearchIndexImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutFoldersIndexRoute = AppLayoutFoldersIndexImport.update({
  id: '/folders/',
  path: '/folders/',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutFavouritesIndexRoute = AppLayoutFavouritesIndexImport.update({
  id: '/favourites/',
  path: '/favourites/',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutFaqSupportIndexRoute = AppLayoutFaqSupportIndexImport.update({
  id: '/faq-support/',
  path: '/faq-support/',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutSoundNameRoute = AppLayoutSoundNameImport.update({
  id: '/sound/$name',
  path: '/sound/$name',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutSubscribePaymentIndexRoute =
  AppLayoutSubscribePaymentIndexImport.update({
    id: '/subscribe/payment/',
    path: '/subscribe/payment/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app/_layout': {
      id: '/_app/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_app/_layout/': {
      id: '/_app/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app/_layout/sound/$name': {
      id: '/_app/_layout/sound/$name'
      path: '/sound/$name'
      fullPath: '/sound/$name'
      preLoaderRoute: typeof AppLayoutSoundNameImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app/_layout/faq-support/': {
      id: '/_app/_layout/faq-support/'
      path: '/faq-support'
      fullPath: '/faq-support'
      preLoaderRoute: typeof AppLayoutFaqSupportIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app/_layout/favourites/': {
      id: '/_app/_layout/favourites/'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof AppLayoutFavouritesIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app/_layout/folders/': {
      id: '/_app/_layout/folders/'
      path: '/folders'
      fullPath: '/folders'
      preLoaderRoute: typeof AppLayoutFoldersIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app/_layout/search/': {
      id: '/_app/_layout/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppLayoutSearchIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app/_layout/subscribe/': {
      id: '/_app/_layout/subscribe/'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof AppLayoutSubscribeIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app/_layout/welcome/': {
      id: '/_app/_layout/welcome/'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AppLayoutWelcomeIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app/_layout/subscribe/payment/': {
      id: '/_app/_layout/subscribe/payment/'
      path: '/subscribe/payment'
      fullPath: '/subscribe/payment'
      preLoaderRoute: typeof AppLayoutSubscribePaymentIndexImport
      parentRoute: typeof AppLayoutImport
    }
  }
}

// Create and export the route tree

interface AppLayoutRouteChildren {
  AppLayoutIndexRoute: typeof AppLayoutIndexRoute
  AppLayoutSoundNameRoute: typeof AppLayoutSoundNameRoute
  AppLayoutFaqSupportIndexRoute: typeof AppLayoutFaqSupportIndexRoute
  AppLayoutFavouritesIndexRoute: typeof AppLayoutFavouritesIndexRoute
  AppLayoutFoldersIndexRoute: typeof AppLayoutFoldersIndexRoute
  AppLayoutSearchIndexRoute: typeof AppLayoutSearchIndexRoute
  AppLayoutSubscribeIndexRoute: typeof AppLayoutSubscribeIndexRoute
  AppLayoutWelcomeIndexRoute: typeof AppLayoutWelcomeIndexRoute
  AppLayoutSubscribePaymentIndexRoute: typeof AppLayoutSubscribePaymentIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutIndexRoute: AppLayoutIndexRoute,
  AppLayoutSoundNameRoute: AppLayoutSoundNameRoute,
  AppLayoutFaqSupportIndexRoute: AppLayoutFaqSupportIndexRoute,
  AppLayoutFavouritesIndexRoute: AppLayoutFavouritesIndexRoute,
  AppLayoutFoldersIndexRoute: AppLayoutFoldersIndexRoute,
  AppLayoutSearchIndexRoute: AppLayoutSearchIndexRoute,
  AppLayoutSubscribeIndexRoute: AppLayoutSubscribeIndexRoute,
  AppLayoutWelcomeIndexRoute: AppLayoutWelcomeIndexRoute,
  AppLayoutSubscribePaymentIndexRoute: AppLayoutSubscribePaymentIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AppLayoutRouteWithChildren
  '/': typeof AppLayoutIndexRoute
  '/sound/$name': typeof AppLayoutSoundNameRoute
  '/faq-support': typeof AppLayoutFaqSupportIndexRoute
  '/favourites': typeof AppLayoutFavouritesIndexRoute
  '/folders': typeof AppLayoutFoldersIndexRoute
  '/search': typeof AppLayoutSearchIndexRoute
  '/subscribe': typeof AppLayoutSubscribeIndexRoute
  '/welcome': typeof AppLayoutWelcomeIndexRoute
  '/subscribe/payment': typeof AppLayoutSubscribePaymentIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof AppLayoutIndexRoute
  '/sound/$name': typeof AppLayoutSoundNameRoute
  '/faq-support': typeof AppLayoutFaqSupportIndexRoute
  '/favourites': typeof AppLayoutFavouritesIndexRoute
  '/folders': typeof AppLayoutFoldersIndexRoute
  '/search': typeof AppLayoutSearchIndexRoute
  '/subscribe': typeof AppLayoutSubscribeIndexRoute
  '/welcome': typeof AppLayoutWelcomeIndexRoute
  '/subscribe/payment': typeof AppLayoutSubscribePaymentIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app/_layout': typeof AppLayoutRouteWithChildren
  '/_app/_layout/': typeof AppLayoutIndexRoute
  '/_app/_layout/sound/$name': typeof AppLayoutSoundNameRoute
  '/_app/_layout/faq-support/': typeof AppLayoutFaqSupportIndexRoute
  '/_app/_layout/favourites/': typeof AppLayoutFavouritesIndexRoute
  '/_app/_layout/folders/': typeof AppLayoutFoldersIndexRoute
  '/_app/_layout/search/': typeof AppLayoutSearchIndexRoute
  '/_app/_layout/subscribe/': typeof AppLayoutSubscribeIndexRoute
  '/_app/_layout/welcome/': typeof AppLayoutWelcomeIndexRoute
  '/_app/_layout/subscribe/payment/': typeof AppLayoutSubscribePaymentIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/'
    | '/sound/$name'
    | '/faq-support'
    | '/favourites'
    | '/folders'
    | '/search'
    | '/subscribe'
    | '/welcome'
    | '/subscribe/payment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sound/$name'
    | '/faq-support'
    | '/favourites'
    | '/folders'
    | '/search'
    | '/subscribe'
    | '/welcome'
    | '/subscribe/payment'
  id:
    | '__root__'
    | '/_app/_layout'
    | '/_app/_layout/'
    | '/_app/_layout/sound/$name'
    | '/_app/_layout/faq-support/'
    | '/_app/_layout/favourites/'
    | '/_app/_layout/folders/'
    | '/_app/_layout/search/'
    | '/_app/_layout/subscribe/'
    | '/_app/_layout/welcome/'
    | '/_app/_layout/subscribe/payment/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app/_layout"
      ]
    },
    "/_app/_layout": {
      "filePath": "_app/_layout.tsx",
      "children": [
        "/_app/_layout/",
        "/_app/_layout/sound/$name",
        "/_app/_layout/faq-support/",
        "/_app/_layout/favourites/",
        "/_app/_layout/folders/",
        "/_app/_layout/search/",
        "/_app/_layout/subscribe/",
        "/_app/_layout/welcome/",
        "/_app/_layout/subscribe/payment/"
      ]
    },
    "/_app/_layout/": {
      "filePath": "_app/_layout/index.tsx",
      "parent": "/_app/_layout"
    },
    "/_app/_layout/sound/$name": {
      "filePath": "_app/_layout/sound/$name.tsx",
      "parent": "/_app/_layout"
    },
    "/_app/_layout/faq-support/": {
      "filePath": "_app/_layout/faq-support/index.tsx",
      "parent": "/_app/_layout"
    },
    "/_app/_layout/favourites/": {
      "filePath": "_app/_layout/favourites/index.tsx",
      "parent": "/_app/_layout"
    },
    "/_app/_layout/folders/": {
      "filePath": "_app/_layout/folders/index.tsx",
      "parent": "/_app/_layout"
    },
    "/_app/_layout/search/": {
      "filePath": "_app/_layout/search/index.tsx",
      "parent": "/_app/_layout"
    },
    "/_app/_layout/subscribe/": {
      "filePath": "_app/_layout/subscribe/index.tsx",
      "parent": "/_app/_layout"
    },
    "/_app/_layout/welcome/": {
      "filePath": "_app/_layout/welcome/index.tsx",
      "parent": "/_app/_layout"
    },
    "/_app/_layout/subscribe/payment/": {
      "filePath": "_app/_layout/subscribe/payment/index.tsx",
      "parent": "/_app/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
